### PR TITLE
Make jupyterlab_pygments a federated labextension

### PR DESCRIPTION
**Pull request by martinRenou**
Generated from https://github.com/jupyterlab/extension-cookiecutter-ts

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

Looks like CI is not triggered on this repo? Or maybe because it's coming from a fork and the workflows are new.

**Comment by jtpio** [comment]
Thanks!

Looks like CI is not triggered on this repo? Or maybe because it's coming from a fork and the workflows are new.

**Comment by jtpio** [comment]
Looks like you would have to rename the branch to `main` so CI can run.

**Comment by martinRenou** [comment]
Thanks that must be it indeed, I will rename it

**Comment by martinRenou** [comment]
Actually I don't have the rights to rename the main branch, I will update the action for now

**Comment by martinRenou** [comment]
Thanks

**Comment by jtpio** [comment]
Looks like CI is failing: https://github.com/jupyterlab/jupyterlab_pygments/runs/5870961151?check_suite_focus=true

**Pull request merged**
